### ISSUE TITLE
failed to start compute node in PROD

### ISSUE THREAD

**Issue by fugangwang** [sdsc/nucleus-service#14]
A user reported that he could not start any compute node in the PROD system.
While emulating the user to do the same action, I was able to replicate the issue. After looking into this and comparing to what we have in DEV, I found this difference:
It looks like during the process the API returned a redirecting URL, which in the DEV it looks like this:
https://comet-nucleus-dev.sdsc.edu/nucleus/v1/computeset/1234
But in the PROD it looks like this:
/nucleus/v1/computeset/1234
So the base url seems not included in the returned redirecting URL.

This currently blocks what the user can do with the compute nodes.

**Comment by dimm0** [comment]
Assigning @tcooper to deploy in prod

**Comment by tcooper** [comment]
The commit 45cb2af resolves the reported error message compute nodes still do not start due to missing configuration on nodes.

**Comment by tcooper** [comment]
Assigning to @dimm0 to fix.

**Comment by tcooper** [comment]
`/opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.sh` checks that `/opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.py` is executable before running.

It's not so it logs the error and doesn't send back the 'node is ready' message.

```
# cat /tmp/computeset_job_notify.sh.out
Python environment
Currently Loaded Modulefiles:
  1) intel/2013_sp1.2.144   2) mkl/11.1.2.144         3) python/2.7.10
/opt/python/bin/python
Python 2.7.10
/opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.py not found/executable

# stat /opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.py
  File: `/opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.py'
  Size: 862         Blocks: 8          IO Block: 4096   regular file
Device: 901h/2305d  Inode: 1064864     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-10-15 12:01:29.000000000 -0700
Modify: 2016-10-15 12:01:29.000000000 -0700
Change: 2016-10-17 16:50:38.917118304 -0700
```

Either make `/opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.py` executable OR change `/opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.sh` to only test for the existence of `/opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.py` and call it with the convention...

```
python /opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.py
```

**Comment by tcooper** [comment]
Above listed issue resolved. New issue...

```
# tail /tmp/computeset_job_notify.sh.out
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/nucleus_service/computeset_job_notify.py", line 7, in <module>
    from nucleus.celery import *
  File "/opt/python/lib/python2.7/site-packages/nucleus_service/nucleus/__init__.py", line 3, in <module>
    from .celery import app as celery_app
  File "/opt/python/lib/python2.7/site-packages/nucleus_service/nucleus/celery.py", line 8, in <module>
    from nucleus import settings
  File "/opt/python/lib/python2.7/site-packages/nucleus_service/nucleus/settings.py", line 24, in <module>
    with open('/var/secrets/cometvc/django_secret') as f:
IOError: [Errno 2] No such file or directory: '/var/secrets/cometvc/django_secret'

# stat /var/secrets/cometvc/django_secret
stat: cannot stat `/var/secrets/cometvc/django_secret': No such file or directory
```
